[package]
name = "respectrum_gui"
version = "0.1.0"
edition = "2018"
default-run = "emul"

[[bin]]
name = "emul"
path = "src/emul.rs"

[dependencies]
librespectrum = { path = "../librespectrum" }
eframe = "^0.14.0"
