[package]
name = "respectrum_iced"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "emul-iced"
path = "src/emul.rs"

[dependencies]
librespectrum = { path = "../librespectrum" }
iced = { version = "0.4", features = ["pure"] }
iced_native = "0.5"
