[package]
name = "respectrum_egui"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "emul-egui"
path = "src/emul.rs"

[dependencies]
librespectrum = { path = "../librespectrum" }
egui = "0.18.0"
egui_extras = "0.18.0"
eframe = "0.18.0"
