[package]
name = "respectrum_tools"
version = "0.1.0"
edition = "2018"

[[bin]]
name = "disasm"
path = "src/disasm.rs"

[dependencies]
librespectrum = { path = "../librespectrum" }
clap = { version = "3.1.6", features = ["derive"] }
