[package]
name = "color_clash"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "cc"
path = "src/main.rs"

[dependencies]
bitflags = "1.3.2"
druid = { git = "https://github.com/linebender/druid.git", features = ["im"] }
